### ISSUE TITLE
Leading row is always ignored

### ISSUE THREAD

**Issue by fthommen** [Rello/analytics#153]
Even w/o specifying "Ignore leading rows", the first row is ignored:
```
Name,Date,Inhabitants
city1,2020-01-01,15000
city1,2020-02-01,13000
city1,2020-03-01,14000
city2,2020-01-01,16000
city2,2020-02-01,17000
city2,2020-03-01,18000
```

results in the following chart:
![image](https://user-images.githubusercontent.com/279232/117581395-d531f400-b0fc-11eb-955c-0ec8031eb389.png)

While when specifying "Ignore leading rows"=1, also the second row is ignored:
![image](https://user-images.githubusercontent.com/279232/117581431-00b4de80-b0fd-11eb-89db-fef276d1b4c0.png)

Neverthless the first row seems to be always ignored, its content seems to matter.  The following, slightly modified table
```
This is some text
city1,2020-01-01,15000
city1,2020-02-01,13000
city1,2020-03-01,14000
city2,2020-01-01,16000
city2,2020-02-01,17000
city2,2020-03-01,18000
```

Results in the following broken chart when "Ignore leading rows" is not specified:
![image](https://user-images.githubusercontent.com/279232/117581544-93ee1400-b0fd-11eb-8b65-0385b9884d9c.png)

While with "Ignore leading rows"=1 the resulting chart is as above (with the missing first data line)

**Comment by Rello** [comment]
Hello,
the first chart is correct, isn´t it?

but your remark shows, that it needs a little better explanation. I will change the sequence of the fields at last.

first, rows can be ignored (e.g. the "some text") in your last example. this can be the case if a file has some leading explanation.

then the extraction starts. it is assumed, that the first row of a file consists the headers. this line is also used to derive the delimiter of the file (, ; ...).
So in the last example, it is wrong because the delimiter " " is recognized in the first row.

So chart 1 is as expected; chart 2 has the header cut due to the offset.
does this help?

**Comment by fthommen** [comment]
> the first chart is correct, isn´t it?

yes ;-)
 
> but your remark shows, that it needs a little better explanation. I will change the sequence of the fields at last.
> 
> first, rows can be ignored (e.g. the "some text") in your last example. this can be the case if a file has some leading explanation.
> 
> then the extraction starts. __it is assumed, that the first row of a file consists the headers. this line is also used to derive the delimiter of the file (, ; ...).__
> So in the last example, it is wrong because the delimiter " " is recognized in the first row.

Ah, __that__ explains it.  This wasn't obvious to me.  I think it would be extremely helpful to add this information or some other abstract format definition to the user manual.


> So chart 1 is as expected; chart 2 has the header cut due to the offset.
> does this help?

Yes absolutely.  Thank you very much for your quick and helpful explanations
