### ISSUE TITLE
[Dashboard] Size/Format of displayed numbers

### ISSUE THREAD

**Issue by araccaine** [Rello/analytics#187]
Firstly, I love this nextcloud app so far :)

My question is, is it possible to format the Dashboard output? As you can see in the cropped screenshot of my Dashboard, there are two numbers too long to display. Is there any chance to format this? Resizing of Dahsboard widgets is not an option I am afraid.  
 
![screenanalyticsdashboard](https://user-images.githubusercontent.com/75312500/128671810-ea8e8aa7-1692-42e5-8f4f-f77bffb09ed5.PNG)

**Comment by Rello** [comment]
oh. good point.
I will have a look.

would a shortening with 106k e.g. help you? or is the whole number important that a change in the sizing would be more wanted?

**Comment by araccaine** [comment]
For this usecase some shortening with *k* as suffix would be sufficient, or even some conversion like `[number] * [factor]`, e.g. `[free space in kilobyte] * 1/1048576` to show it in Gigabyte?

on the other hand, if one can show the whole number beneath the heading would be great, too, i think.

**Comment by Rello** [comment]
Hi,

I am playing and I could enable a generic K/M unit
I think it should be sufficient for the Dashboard to have it shortened that much.

**BUT**: its a generic /1000 calculation. I can not use different factors because I do not know the unit (is it € or megabyte). not 100% perfect for your case, but still better than now.

what do you think?

![Bildschirmfoto 2021-10-30 um 23 39 33](https://user-images.githubusercontent.com/13385119/139559115-822e86b3-8d4a-4e3b-90d7-795f5aee3536.png)

**Comment by araccaine** [comment]
Oh, I didn't get any notification for your last reply! Sorry about my late answer. Your solution works for me :)

**Comment by araccaine** [comment]
Thank you again, works very well!
