### ISSUE TITLE
Zoom in charts

### ISSUE THREAD

**Issue by tobiasKaminsky** [Rello/analytics#246]
Sometimes I only want to see parts of a graph, which I currently try to do via filters, but probably a zoom would also be enough/more easier:
https://www.chartjs.org/chartjs-plugin-zoom/latest/guide/

It seems to be easy to be added, and can be enabled on demand, maybe?

**Comment by Rello** [comment]
Hi,
yes, sounds pretty straight out of the box.
I will give it a try.

what I saw from the demo I don´t like it that much, because e.g. mouse wheel is confusing.
I remember from highcharts there was a plugin to select a range in the chart and then it zoomed to that selection. don´t know if it exists.
But your suggestion would be a quick win.

there are many plugins which might be helpfull for the one or the other. as long as they just need to be included and no parameters are required, I am thinking about a way to do this dynamic perhaps?
e.g. you put the plugin into a special folder and you can use it. would make it flexible for all users.
what do you think?

**Comment by tobiasKaminsky** [comment]
> what I saw from the demo I don´t like it that much, because e.g. mouse wheel is confusing.
> I remember from highcharts there was a plugin to select a range in the chart and then it zoomed to that selection. don´t know if it exists.

Indeed, HighChart's plugin was more intuitive.

But here it seems to work similar:
https://www.chartjs.org/chartjs-plugin-zoom/samples/drag/linear.html

**Comment by Rello** [comment]
hallo @tobiasKaminsky 
I just tried. I think for AP only the horizontal one makes sense.
have a look here
https://nc-test.scherello.de/nextcloud/apps/analytics/p/7Ht1RjTVwIHKTzu
what do you think?

I just need to figure out where to put the reset-zoom

**Comment by tobiasKaminsky** [comment]
Wow. This is awesome!



> I just need to figure out where to put the reset-zoom

Maybe here?
![image](https://user-images.githubusercontent.com/5836855/155483127-47804c9e-dc25-4072-b78b-8afd48af07b8.png)

(just found this icon when searching for "reset zoom button").

**Comment by Rello** [comment]
Hätte sonst neben "Legende" gedacht. wäre einfacher als ein chart overlay dass sich nicht beeinflusst.
hab leider noch nix gefunden es "on demand" einzublenden. mal sehen
