### ISSUE TITLE
Faster report creation

### ISSUE THREAD

**Issue by JosephChataignon** [Rello/analytics#293]
Currently when creating a report, 3 different parameters have to be defined before the report can be created. If one is missing, the report cannot be created. Since they all can be changed later, it might be more convenient to authorize the creation of empty reports, using default values, like:
- for the report title: "Untitled report"
- for the data source type, either "real-time" or the other
- for chart type, maybe "table", or authorize empty reports (where charts can be added later)

**Comment by Rello** [comment]
Hi,
the problem is, that the selection of realtime+datasource or stored data (existing or new) are not exchangeable after their creation due to technical reasons.
I created the wizard to make it as simple as possible and don´t see a good approach to include a "dummy report" button anywhere for several combinations.

But one idea: I can at least populate the report title with a default content. then this screen does not have a mandatory input. same as the last screen.
But there is no way around the selection on the second wizard screen.

Thank you for your suggestion
