### ISSUE TITLE
[Enhancement] Multicolumn in saved Datasets

### ISSUE THREAD

**Issue by sirdrakeistda** [Rello/analytics#296]
When creating a dataset I could choose between Realtime Dataset and saved Dataset. If I use the same source (e.g. https://covid19.who.int/WHO-COVID-19-global-data.csv), leave the column option empty and choose Table as display option. The realtime dataset has multiple columns, but the saved dataset has only one three columns. My idea was to import the dataset once and then create different reports from different columns. This would reduce the amount of synchronizations for me.

Solution:
- Allow importing and saving the complete multicolumn dataset
- Add option to choose columns for reports made by existing datasets

**Comment by Rello** [comment]
Hello,
yes, thats on the roadmap since quite some time. the enhancement will be significant.
As the datastructures are given by Nextcloud, it will always be based on a more or less fixed table structure with a given number of columns.
while I plan to extend them, I have to see how it can be done.

I am collecting the requests with this request and come back once I start with the enhancement
https://github.com/Rello/analytics/issues/19
