### ISSUE TITLE
Filter variables to use same time format like chart

### ISSUE THREAD

**Issue by PVince81** [Rello/analytics#321]
### Steps (inferred from my use case)

1. Setup a time series chart
2. Populate with data from a week ago, and also a few values from an hour ago, using the format: `["Temperature","1669138201","18.36"]` for the values where the first column is "Object" and the second is the timestamp
3. Set chart options to `{"scales": {"xAxes": {"time": {"parser" : "X"}}}}` to have the time properly recognized
4. Open the filter dialog and set it to "Date", "greater than" and "%today%" as per documentation

### Expected result
Chart updates and only shows values of today.

### Actual result
And error says that no values are found
<img width="643" alt="image" src="https://user-images.githubusercontent.com/277525/203382213-6bba7085-a36a-44e6-b4bd-877247d20106.png">

### More information
Same result with `%last14days%` or any similar value.

After looking I realized that maybe I need a format string, so I changed it to `%today% (X)` since I'm using Unix timestamps, but also "no data". So not sure if it's a bug or something missing in the docs about the format.

In general I find it cumbersome to have to add format strings in multiple places as I'd hope the app would already know what format I want for this column, but I understand that it might be due to the generic design of the data structure.

**Comment by Rello** [comment]
Hi,
your findings are correct. 2 topics here

1. the parser for the variables it not really working. It was prepared but only properly implemented for one of my usecases. Yours is a good example of missing features. I will take care. 
---
2. I agree with you that its not usefull to place this in several places. I have it as a todo since a while already, but did not have a proper solution yet

- one way would be that I search the chart options for a parser setting and reuse this in several other places.
- as the parser is a frequent request and the option array is not very user friendly, I think about adding another setting (e.g. dropdown with most used presets + own values). this would be far more userfriendly and would be reused in all places in the background.

what do you think?

**Comment by Rello** [comment]
For the moment, can you please try the format `(U)`?
PHPs date() is using this for the timestamp. just to try if this is working. the both questions remain

**Comment by PVince81** [comment]
Just passing by to say That with `(U)` the "%today%" filter works fine! (on the released version)

I'll check your comments later
