### ISSUE TITLE
Error on Dataload

### ISSUE THREAD

**Issue by sirdrakeistda** [Rello/analytics#328]
# Datasource
https://covid19.who.int/WHO-COVID-19-global-data.csv
# Errorlog:
```
[PHP] Fehler: Error: Undefined array key "dimension1" at /var/www/nextcloud/apps/analytics/lib/Controller/DatasourceController.php#255 at <<closure>>

0. /var/www/nextcloud/apps/analytics/lib/Controller/DatasourceController.php line 255
   OC\Log\ErrorHandler::onError()
1. /var/www/nextcloud/apps/analytics/lib/Controller/DatasourceController.php line 150
   OCA\Analytics\Controller\DatasourceController->filterData()
2. /var/www/nextcloud/apps/analytics/lib/Controller/OutputController.php line 116
   OCA\Analytics\Controller\DatasourceController->read()
3. /var/www/nextcloud/apps/analytics/lib/Controller/OutputController.php line 83
   OCA\Analytics\Controller\OutputController->getData()
4. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 225
   OCA\Analytics\Controller\OutputController->read()
5. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 133
   OC\AppFramework\Http\Dispatcher->executeController()
6. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
7. /var/www/nextcloud/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
8. /var/www/nextcloud/lib/base.php line 1047
   OC\Route\Router->match()
9. /var/www/nextcloud/index.php line 36
   OC::handleRequest()

GET /index.php/apps/analytics/data/1
from 141.70.9.150 by user at 2023-01-07T10:55:15+00:00
```

**Comment by Rello** [comment]
@sirdrakeistda can you send me the options of the datasource, which ich selected?
thank you

**Comment by sirdrakeistda** [comment]
Name: Corona Daten (WHO)
Group: Corona
Source: csv
URL: https://covid19.who.int/WHO-COVID-19-global-data.csv
ignore lines: (empty)
choose columns: (empty)
Display type: table
Chart type: line
Chart option: (empty)
Data option: (empty)

Thresholds:
red Germany 41550
green Germany <= 19085
yellow Germany < 41550

**Comment by Rello** [comment]
Hi,

the reason is, that you loaded it unfiltered. for - current - technical limitations, internal data can only have 3 columns with the value in the last column.
if you filter the columns, it works. I recommend to switch the first date column with the country (see the "selected columns") to have the date in the second column. then you can use standard timeline reporting.

Does this help for your issue? I need to check the error output for your case...

![Bildschirm­foto 2023-01-16 um 14 10 53](https://user-images.githubusercontent.com/13385119/212685968-999de859-da2e-4f80-8997-d9054c5abdc7.png)
Note: the "Limit" will be added with the next release...

![Bildschirm­foto 2023-01-16 um 14 11 24](https://user-images.githubusercontent.com/13385119/212686053-a5265466-7343-4473-b2e9-0e8eef01a56b.png)
