### ISSUE TITLE
Charts: secondary axis

### ISSUE THREAD

**Issue by ernesst** [Rello/analytics#36]
Hello, 

Thanks for the application, seems very neat. I appreciate the notification threshold. 
In case of different magnitude order between objects, would it be possible to implement the possibility to have a secondary axis ? 

For instance : Temperature, humidity, AIQ level are difficult to follow on the same axis. 

Thanks

**Comment by Rello** [comment]
Hello,

chartjs has this feature - the challenge will be to find a way to make it simple to use.
will need to look at it. I put it on the roadmap

**Comment by Rello** [comment]
Hello @ernesst 
just to let you know that I am working on the feature at this moment already.

![Screenshot 2020-06-23 at 23 16 48](https://user-images.githubusercontent.com/13385119/85464179-9f992080-b5a7-11ea-8ea9-996b45fcff3a.png)

The issue is to create a meaningful UI.
I implemented the "raw" version via an additional option-input box. but this is not user friendly yet
![Screenshot 2020-06-23 at 23 17 51](https://user-images.githubusercontent.com/13385119/85464296-c3f4fd00-b5a7-11ea-98df-b4149878de37.png)

the inputs for a secondary axis would be:
- Chart Options: `{"scales": {"yAxes": [{},{"id":"B","position":"right"}]}}`
- Data Options: `[{"yAxisID":"B"},{},{"yAxisID":"B"},{}]`

first is activating a secondary axis. second is assigning the datasets (in my case the first and 3rd one) to the axis
do you have an idea how this could be done in a UI?
any example?

**Comment by ernesst** [comment]
If it's UI only

A check box <= "Secondary axis"  (I would consider to let the secondary axis every time on the right)
If tick then below shows up :
The list of trace could be displayed with a drop-down menu on the right allowing to select Y1 or Y2 :
- Trace 1 => [Y1]
- Trace 2 => [Y2]
- Trace3 => [Y1]

and with a box to click on to save.

I'll try to find some examples.

**Comment by Rello** [comment]
I am testing an option-popup for this. 
this will display all distinct values of the first dimension (= your "Traces"). Then I can also add chart options to change e.g. one dataseries to line/column to combine the types

![Screenshot 2020-06-26 at 10 14 26](https://user-images.githubusercontent.com/13385119/85835748-df255f80-b795-11ea-82e9-6a8fa149c63c.png)

**Comment by Rello** [comment]
![Screenshot 2020-06-27 at 14 38 15](https://user-images.githubusercontent.com/13385119/85925886-af607f80-b89b-11ea-8d4b-10e13335b52d.png)

**Comment by ernesst** [comment]
Looks neat !!
FYI: I'm currently moving across country....my server is in a container. I'll be able to test in a month and half.

**Comment by Rello** [comment]
Charts: customisation of single data-series #44
