### ISSUE TITLE
NC20: Dashboard Widget

### ISSUE THREAD

**Issue by Rello** [Rello/analytics#61]
- [x] Register Widget
- [x] App icon
- [x] Mark reports as favorite #63
- [x] Favorites are shown in Dashboard
- [ ] <del>recent reports</del>
- [ ] <del>recent updates</del>

**Comment by Rello** [comment]
Beta 1

![Bildschirmfoto 2020-08-18 um 22 51 57](https://user-images.githubusercontent.com/13385119/90564288-6fd05880-e1a5-11ea-93eb-ad41630e9ddb.png)

**Comment by Rello** [comment]
https://github.com/nextcloud/server/issues/20930

**Comment by Rello** [comment]
![Bildschirmfoto 2020-08-20 um 21 28 39](https://user-images.githubusercontent.com/13385119/90816171-1f373780-e32c-11ea-87f4-6ce7f99c4f14.png)

**Comment by Rello** [comment]
![Bildschirmfoto 2020-09-08 um 14 48 39](https://user-images.githubusercontent.com/13385119/92478392-63f31780-f1e2-11ea-9f04-2b7992c594d1.png)

**Comment by jancborchardt** [comment]
Really amazing progress @Rello, looks so nice! :) 

I would say it’s fine to have the simpler (last) version. The relevant numbers could be integrated either in subline or the visualization, for example:
- Plant sensors: What is "90"? I assume the level of watering? So there I’d say the graph is enough, as it represents the number. If the water level sinks to dangerous levels, the graph could go red.
- Analytics downloads: I would say the download numbers should go in the subline. The version number is less interesting, as it will always be the latest anyway?
- HTML Grabber: What is exactly indicated here? I assume when changes on a HTML page were made and then subsequently saved? In that case the chart should be a bar chart, and I would say the site name in the first row, and in the second row: "Last update 2 days ago" for example.
- Notification test: Looks good with just the number as well – I guess instead of "red KPI" it would show some more informative text possibly? Like "Below monthly goal" or smth like that – cause now it’s just reading out what the number visualizes.
- Demo report: Looks good I guess? Not sure what kind of data it is though, then I could make a more informed comment. :)

General design feedback:
- Note the text is ellipsized very early, it can go on for a bit more. :)
- The graph in general looks nicer without the fill below cause it is very blocky. Or the fill could be faded to transparency, like in Apple Stocks?
- If you don’t mind, I’d propose that the app icon for Analytics could be simplified :) E.g. https://thenounproject.com/term/chart/2500312/ or even simpler: https://material.io/resources/icons/?search=chart&icon=bar_chart&style=baseline

As said, looks super good overall! :) Feel free to post more examples from different types of reports if that feedback is helpful.

**Comment by Rello** [comment]
![Bildschirmfoto 2020-09-09 um 23 52 44](https://user-images.githubusercontent.com/13385119/92658872-8fb3f180-f2f7-11ea-8b9f-a171d74285ec.png)

**Comment by Rello** [comment]
@jancborchardt 
thank you for your suggestions. I was searching for the logo for some time. It is now much simpler as before but still distinguishable from the Polls app. see the above screenshots
