### ISSUE TITLE
MQTT as datasource

### ISSUE THREAD

**Issue by roadfox** [Rello/analytics#90]
Very nice App, thanks alot!

As more and more iot devices and home automation projects are using mqtt it would be great to have an MQTT Datasource where you can subscribe to a topic.

regards
Andi

**Comment by tioannidis** [comment]
is there any update?

**Comment by Rello** [comment]
hello,
not at the moment. MQTT would require a client/server implementation if I am not wrong. This would be definitely something that would be implemented into an app add-on (separate app to be installed; due to the complexity involved).

But as I am currently focusing on the core features of Analytics, I can´t put it on the schedule yet.

**Comment by Rello** [comment]
closing for now
